### PR TITLE
Python3 compatibility

### PR DESCRIPTION
**Pull request by PhrankBrochu**
Passes all tests on Travis, passes tests in both Py2 and Py3 on two platforms (personal pc and colosse)

### CODE REVIEW

**Comment by aldro61** [comment]
Would be good to make travis run the tests in Python 2 and 3. I know that this can be done, but I'm not sure how. I can look into this if you want.

**Comment by plpla** [comment]
Could you also update the training_time example so that the full package is compatible with python3?

**Comment by PhrankBrochu** [comment]
Used the sklearn contained version because I copy-pasted from other code, i'll edit tomorrow morning to separate version of six.

**Comment by PhrankBrochu** [comment]
Forgot the training time example, I'll modify it also.

**Pull request closed without merging**
